#
# appveyor.yml
#
branches:
  only:
    - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Skipping commits affecting specific files (GitHub only).
skip_commits:
  files:
    - docs/*
    - '**/*.html'

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf false

install:
  - vcpkg install --recurse sqlite3[tool] curl[tool]

# to disable automatic builds
build: off

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - cmd: set PATH=C:\Qt\5.9\msvc2015_64\bin;C:\tools\vcpkg\installed\x86-windows\tools;C:\tools\vcpkg\installed\x86-windows\tools\curl;%PATH%
  - cmd: echo %PATH%
  - cmd: configure.bat
  - cmd: cd src
  - cmd: nmake install
  - cmd: cd ..\tools
  - cmd: nmake install
  - cmd: cd test
  - cmd: releasetest\releasetest.bat
